### ISSUE TITLE
Replace no longer maintained, or hijacked http://extension.remotedev.io

### ISSUE THREAD

**Issue by adaliszk** [Marcisbee/exome#12]
Hello,

Looks like the advertised `http://extension.remotedev.io/` domain has been hijacked or is no longer being maintained, at least from my location in Germany. Right now, it loads an OnlyFans page, probably not the intended browser extension to be installed 😄

**Comment by Marcisbee** [comment]
Haha yikes 😄 Thanks, wasn't aware of it, will fix
