### ISSUE TITLE
Preact compatibility ? 

### ISSUE THREAD

**Issue by samueldrai** [Marcisbee/exome#4]
Hi @Marcisbee 
Congrats on the great lib. Really smart and efficient way to manage state.
I am currently working on a side-project using Preact. Is there any chance to see a preact version that doesn't need the `compat` layer to work?

Would be happy to help if I can. :) 

Maybe we could simply replace exports in `https://github.com/Marcisbee/exome/blob/main/src/react.ts` using Preact versions of the hooks referenced in this file. :)

**Comment by Marcisbee** [comment]
Hey, thanks!

Yeah, adding Preact was in my todo list. Since the implementation is basically the same, I think we can just copy `react.ts` and use `preact` imports inside it.

Will create a PR in just a sec.

**Comment by samueldrai** [comment]
Thanks for your reactivity @Marcisbee 
Would be happy to open the PR if you're happy with that :)

**Comment by Marcisbee** [comment]
I'm open for contributions!
But I was so excited to add this feature that I went ahead and already added Preact support in [v0.8.6](https://github.com/Marcisbee/exome/releases/tag/v0.8.6) just now before I read that you want to actually contribute 😬 
Sorry, hope it's all right.
