### ISSUE TITLE
DevTools error

### ISSUE THREAD

**Issue by kg-currenxie** [Marcisbee/exome#9]
I get this error when i add the devtools middleware, and call a store method for the _first time_. When i refresh the page, i dont get the error anymore. 

And ofc, no error without the middleware. 

![Screenshot 2021-06-28 at 17 44 30](https://user-images.githubusercontent.com/48229166/123616109-8b31d880-d838-11eb-871e-0c72199a7399.png)

Thx :) Love exome <3

**Comment by Marcisbee** [comment]
Thanks!
Hmm, I can't seem to reproduce the issue. What build tool are you using?
Could you maybe share a reproducible codesandbox?

**Comment by kg-currenxie** [comment]
I just use webpack (v4). I'll try if i can reproduce. My app is medium sized, so there could be a combination of things in there :)

**Comment by kg-currenxie** [comment]
Made a quick test inside my own app first. It seems like a webpack thing to me:

Changed from
```
export const alertStore = new AlertStore()

...

alertStore().addAlert()
```

To
```
export const alertStore = new AlertStore()

export function getAlertStore(): AlertStore {
  return alertStore
}

...

getAlertStore().addAlert()
```

and it works. 🤷 
So don't think anything wrong with exome :)
